version: '3'

services:
  webserver:
    container_name: canteen-be
    image: canteen-be:latest
    ports:
      - "3333:80"
    env_file:
      - ".env"
  db:
    image: mysql:8.0.28
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mysql8-local
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "secret"
    restart: always

network:
